{
 "title": "Hive Vitals Overview",
 "tags": [
  "overview",
  "hive"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "query": "grafana-azure-monitor-datasource"
   }
  ]
 },
 "panels": [
  { "title": "Resources Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load Balancer SNAT Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Used SNAT Ports",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.network/loadbalancers",
      "dimensionFilters": [],
      "metricName": "UsedSnatPorts",
      "metricNamespace": "microsoft.network/loadbalancers",
      "resourceGroup": "AZURE_LB_RESOURCE_GROUP",
      "resourceName": "kubernetes",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "SNAT Connection Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "SnatConnectionCount",
      "metricNamespace": "microsoft.network/loadbalancers",
      "resourceGroup": "AZURE_LB_RESOURCE_GROUP",
      "resourceName": "kubernetes",
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    }
   ]
  },
  {
   "title": "Postgres Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "CPU %",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "cpu_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resources": [
       { "resourceGroup": "AZURE_POSTGRES_RESOURCE_GROUP", "resourceName": "AZURE_POSTGRES_SERVER_NAME" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "RAM %",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "memory_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resources": [
       { "resourceGroup": "AZURE_POSTGRES_RESOURCE_GROUP", "resourceName": "AZURE_POSTGRES_SERVER_NAME" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "IOPS Avg",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "iops",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resources": [
       { "resourceGroup": "AZURE_POSTGRES_RESOURCE_GROUP", "resourceName": "AZURE_POSTGRES_SERVER_NAME" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Storage %",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "dimensionFilters": [],
      "metricName": "storage_percent",
      "metricNamespace": "microsoft.dbforpostgresql/flexibleservers",
      "resources": [
       { "resourceGroup": "AZURE_POSTGRES_RESOURCE_GROUP", "resourceName": "AZURE_POSTGRES_SERVER_NAME" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    }
   ]
  },
  {
   "title": "Kafka Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Incoming Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "AZURE_EVENTHUB_RESOURCE_GROUP",
      "resourceName": "AZURE_EVENTHUB_CLUSTER_NAME",
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "Outgoing Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "resourceGroup": "AZURE_EVENTHUB_RESOURCE_GROUP",
      "resourceName": "AZURE_EVENTHUB_CLUSTER_NAME",
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    }
   ]
  },
  {
   "title": "Kubernetes Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "CPU % Usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "node_cpu_usage_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "resourceGroup": "AZURE_KUBERNETES_RESOURCE_GROUP",
      "resourceName": "AZURE_KUBERNETES_CLUSTER_NAME",
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "RAM % Usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "node_memory_rss_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "resourceGroup": "AZURE_KUBERNETES_RESOURCE_GROUP",
      "resourceName": "AZURE_KUBERNETES_CLUSTER_NAME",
      "timeGrain": "auto"
     },
     "subscription": "AZURE_SUBSCRIPTION_ID"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"usage-.*\"}",
     "legendFormat": "Process Memory - {{pod}}"
    }
   ]
  },
  { "title": "Services CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Usage Service CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{pod=~\"usage-service-.*\"}[$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Usage Ingestor Service CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{pod=~\"usage-ingestor-service-.*\"}[$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Schema service memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{pod=~\"schema-.*\"}"
    }
   ]
  },
  {
   "title": "Schema Service CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{pod=~\"schema-.*\"}[$__range])"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Collected Operations per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    {
     "expr": "sum(rate(usage_operations_total[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Buffer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate(usage_buffer_flushes_total[$__rate_interval]))",
     "legendFormat": "Flushes"
    }
   ]
  },
  {
   "title": "Operations per second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(usage_operations_total[$__rate_interval]))",
     "legendFormat": "Operations"
    }
   ]
  },
  {
   "title": "Collect duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(usage_raw_collect_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Compress and Stringify duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(usage_raw_collect_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Kafka duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(usage_raw_kafka_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Size estimation error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(usage_size_estimation_error{quantile=\"0.99\"}[$__rate_interval])) * 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reports",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(usage_reports_total[$__rate_interval]))",
     "legendFormat": "Received reports"
    },
    {
     "expr": "sum(rate(usage_reports_legacy_format_total[$__rate_interval]))",
     "legendFormat": "Reports in legacy format"
    }
   ]
  },
  {
   "title": "Status of operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum(rate(usage_operation_failures[$__rate_interval]))",
     "legendFormat": "Operations that failed to be collected"
    },
    {
     "expr": "sum(rate(usage_operations_invalid_total[$__rate_interval]))",
     "legendFormat": "Invalid and dropped operations"
    }
   ]
  },
  {
   "title": "Reason of dropping operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum by (reason) (rate(usage_operations_invalid_total[$__rate_interval]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "Rate Limit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Operations Rate Limit Events by Org",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (orgName, orgId) (rate_limited_operations_events_count_total)",
     "legendFormat": "{{orgName}} | {{orgId}}"
    }
   ]
  },
  {
   "title": "Operations Reports Dropped by Usage service",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(orgId) (usage_rate_limit_dropped_total)",
     "legendFormat": "{{orgId}}"
    }
   ]
  },
  { "title": "Ingestor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Collected and Processed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(usage_operation_writes_total[$__rate_interval]))",
     "legendFormat": "Collected"
    },
    {
     "expr": "sum(rate(usage_ingested_operation_writes_total[$__rate_interval]))",
     "legendFormat": "Processed"
    }
   ]
  },
  {
   "title": "Collected / Processed ratio",
   "type": "stat",
   "description": "100% means it processed the same amount as it collects.\n\nHigher then 100% means we process more than collected. It's fine if we processed less then collected few minutes ago, but if it's continuously above 100%, something went wrong.\n\nLower than 100% means we lack of processing power.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(usage_ingested_operation_writes_total[$__rate_interval])) / sum(rate(usage_operation_writes_total[$__rate_interval]))",
     "legendFormat": "collected / processed"
    }
   ]
  },
  {
   "title": "Processing duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(usage_ingestor_process_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Write duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (destination, query, le) (rate(usage_ingestor_write_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{destination}} {{query}}"
    }
   ]
  },
  {
   "title": "Processed operations per pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(usage_ingested_operation_writes_total[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Operations per pod",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(pod) (rate(usage_ingested_operation_writes_total[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sum(rate(usage_ingested_operation_writes_total[$__rate_interval]))",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rate(usage_ingested_operation_failures[$__rate_interval]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Registry of Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "sum(rate(usage_ingested_operation_registry_writes[$__rate_interval]))",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(rate(usage_ingested_operation_registry_failures[$__rate_interval]))",
     "legendFormat": "Failed"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "HTTP Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(usage_http_requests_total[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Recevied bytes per message",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(usage_ingestor_report_message_bytes{quantile=\"0.99\"})",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Normalization cache misses",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(usage_ingestor_normalize_cache_misses_total[$__rate_interval])/rate(usage_ingestor_operations_total[$__rate_interval]))",
     "legendFormat": "Cache misses"
    }
   ]
  },
  { "title": "Tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "Latency to Tokens",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, status) (rate(usage_tokens_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "targets": [
    {
     "expr": "sum(irate(usage_http_requests_no_token[$__rate_interval]))",
     "legendFormat": "No token"
    },
    {
     "expr": "sum(irate(usage_http_requests_invalid_token[$__rate_interval]))",
     "legendFormat": "Not in DB"
    },
    {
     "expr": "sum(rate(usage_http_requests_no_access[$__rate_interval]))",
     "legendFormat": "No access"
    }
   ]
  },
  {
   "title": "Requests to Tokens service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "targets": [
    {
     "expr": "sum(irate(usage_tokens_requests_total[$__rate_interval]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(irate(usage_tokens_requests_total[$__rate_interval]))-sum(irate(usage_tokens_cache_hits_total[$__rate_interval]))",
     "legendFormat": "Cache misses"
    }
   ]
  }
 ]
}